# Generated by Django 3.2.10 on 2022-01-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
