# Generated by Django 3.2.10 on 2022-01-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_rename_username_user_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
